/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pck;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author intel
 */
public class LoginLogin extends javax.swing.JFrame {
    static Connection connection;
    static String url;
    static Statement st;
    static ResultSet rs;
    String dbtbl;
    static Statement st1;
    static ResultSet rs22;
    int count = 0;
    Connection Conn = null;
    ResultSet rs1 = null;
    ResultSet rs2 = null;
    ResultSet rs4 = null;
    PreparedStatement pst5 = null;
    PreparedStatement pst4 = null;
    PreparedStatement pst3 = null;
    PreparedStatement pst2 = null;
    PreparedStatement pst1 = null;
    PreparedStatement pst = null;
    private ImageIcon format = null;
    String id = "";
    
    public int search(String id, String name) throws SQLException, ClassNotFoundException{
        Class.forName("com.mysql.jdbc.Driver");
        url = "jdbc:mysql://localhost:3306/pos";
        connection = DriverManager.getConnection(url, "root", "");
        st = connection.createStatement();
        rs = st.executeQuery("Select * From admin Where adminID= '" + id + "'  " + "and fname = '" + name + "'");
        if (rs != null)
            return 1;
        else
            return 0;
    }

    /**
     * Creates new form Login
     */
    public LoginLogin() {
        initComponents();
    }

    private void signin(){
        String adminName = userText.getText();
        String adminPass = userPass.getText();
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection Conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pos", "root", "");
            Statement statement = Conn.createStatement();
            ResultSet getData = statement.executeQuery( "select * from admin where fname = " + "'" + adminName + "' and Password = '" + adminPass + "'" );
            String getUsername = "", getPassword = "";

            if ( getData.next()){
                getUsername = getData.getString("username");
                getPassword = getData.getString("password");
            }
            if (adminName.equals("") && adminPass.equals(""))
                JOptionPane.showMessageDialog(null, "Enter the admin name and password", "Error", JOptionPane.ERROR_MESSAGE);
            else if (adminName.equals(getUsername) && adminPass.equals(getPassword)){
                Admin page = new Admin();
                page.setVisible(true);
                setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog( null, "Invalid admin name or Password", "Error", JOptionPane.ERROR_MESSAGE );
                userText.setText("");
                userPass.setText("");
                //userPass.setText("1234567890");
            }
        }
        catch (Exception e){}
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        usernametxt = new javax.swing.JLabel();
        passtxt = new javax.swing.JLabel();
        LoginBtn = new javax.swing.JButton();
        cbx = new javax.swing.JComboBox();
        userPass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hiddenlbl1 = new javax.swing.JLabel();
        hiddenlbl2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 153));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        userText.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        userText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTextActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("Login as:");

        usernametxt.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        usernametxt.setText("Username:");

        passtxt.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        passtxt.setText("Password:");

        LoginBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        LoginBtn.setText("Login");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        cbx.setBackground(new java.awt.Color(204, 255, 204));
        cbx.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        cbx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "SalesPerson", "WarehouseManager" }));
        cbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxActionPerformed(evt);
            }
        });

        userPass.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pck/final-logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userPass, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(LoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(325, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernametxt)
                    .addComponent(passtxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoginBtn)
                .addGap(64, 64, 64))
        );

        hiddenlbl1.setEnabled(false);
        hiddenlbl1.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hiddenlbl2)
                    .addComponent(hiddenlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(554, 554, 554))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(hiddenlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 442, Short.MAX_VALUE)
                .addComponent(hiddenlbl2)
                .addGap(175, 175, 175))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(936, 656));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxActionPerformed
    }//GEN-LAST:event_cbxActionPerformed

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        if(cbx.getSelectedItem().equals("SalesPerson")){
            String adminName = userText.getText();
            String adminPass = userPass.getText();
            //String id;
            
            try{
                String id = "";
                Class.forName("com.mysql.jdbc.Driver");
                Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/pos", "root", "");
                Statement statement = connection.createStatement();
                ResultSet getData = statement.executeQuery( "select * from admin where fname = " + "'" + adminName + "' and Password = '" + adminPass + "'" );
                //ResultSet getData2 = statement.executeQuery( "select * from login_tbl where id = " + "'" + id + "'" );
                String getUsername = "", getPassword = "";

                if ( getData.next()){
                    getUsername = getData.getString("fname");
                    getPassword = getData.getString("password");
                }
                if (adminName.equals("") && adminPass.equals(""))
                    JOptionPane.showMessageDialog(null, "Enter Username and Password", "Error", JOptionPane.ERROR_MESSAGE);
                else if (adminName.equals(getUsername) && adminPass.equals(getPassword)){
                    CustomerAcc page = new CustomerAcc();
                    JOptionPane.showMessageDialog(null, "Login Successful");
                    page.setVisible(true);
                    setVisible(false);
                    CustomerAcc.namelbl.setText(userText.getText());
                    SelectionSelection.namelbl.setText(userText.getText());
                    //st.executeUpdate("Insert into history(" + "Id,username," + "date" + ") VALUES ('" + userText.getText() + "','" + userText.getText() + "','" + userPass.getText() + "')");
                }
                else{
                    JOptionPane.showMessageDialog( null, "Invalid Username or Password", "Error", JOptionPane.ERROR_MESSAGE );
                    userText.setText("");
                    userPass.setText("");
                    //userPass.setText("1234567890");
                }
            }
            catch (Exception e){}
        }
        
        else if(cbx.getSelectedItem().equals("Admin"))
        {
            String adminName = userText.getText();
            String adminPass = userPass.getText();
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/pos", "root", "");
                Statement statement = connection.createStatement();
                ResultSet getData = statement.executeQuery( "select * from admin where fname = " + "'" + adminName + "' and Password = '" + adminPass + "'" );
                String getUsername = "", getPassword = "";
            
                if ( getData.next()){
                    getUsername = getData.getString("fname");
                    getPassword = getData.getString("password");
                }
                if (adminName.equals("") && adminPass.equals(""))
                    JOptionPane.showMessageDialog(null, "Enter Username and Password", "Error", JOptionPane.ERROR_MESSAGE);
                else if (adminName.equals(getUsername) && adminPass.equals(getPassword)){
                    Admin page = new Admin();
                    JOptionPane.showMessageDialog(null, "Login Successful");
                    
                    page.setVisible(true);
                    setVisible(false);
                    //st.executeUpdate("Insert into history(" + "Id,username," + "date" + ") VALUES ('" + userText.getText() + "','" + userText.getText() + "','" + userPass.getText() + "')");
                    //history();
                    CustomerAcc.namelbl.setText(userText.getText());
                    SelectionSelection.namelbl.setText(userText.getText());
                }
                else{
                    JOptionPane.showMessageDialog( null, "Invalid Username or Password", "Error", JOptionPane.ERROR_MESSAGE );
                    userText.setText("");
                    userPass.setText("");
                    //userPass.setText("1234567890");
                }
            }
            catch (Exception e){}
        }
        
        else if(cbx.getSelectedItem().equals("WarehouseManager"))
        {
            String adminName = userText.getText();
            String adminPass = userPass.getText();
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/pos", "root", "");
                Statement statement = connection.createStatement();
                ResultSet getData = statement.executeQuery( "select * from admin where fname = " + "'" + adminName + "' and Password = '" + adminPass + "'" );
                String getUsername = "", getPassword = "";
            
                if ( getData.next()){
                    getUsername = getData.getString("fname");
                    getPassword = getData.getString("password");
                }
                if (adminName.equals("") && adminPass.equals(""))
                    JOptionPane.showMessageDialog(null, "Enter Username and Password", "Error", JOptionPane.ERROR_MESSAGE);
                else if (adminName.equals(getUsername) && adminPass.equals(getPassword)){
                    Warehouse page = new Warehouse();
                    JOptionPane.showMessageDialog(null, "Login Successful");
                    page.setVisible(true);
                    setVisible(false);
                    //st.executeUpdate("Insert into history(" + "Id,username," + "date" + ") VALUES ('" + userText.getText() + "','" + userText.getText() + "','" + userPass.getText() + "')");
                    //history();
                    CustomerAcc.namelbl.setText(userText.getText());
                    SelectionSelection.namelbl.setText(userText.getText());
                }
                else{
                    JOptionPane.showMessageDialog( null, "Invalid Username or Password", "Error", JOptionPane.ERROR_MESSAGE );
                    userText.setText("");
                    userPass.setText("");
                    //userPass.setText("1234567890");
                }
            }
            catch (Exception e){}
        }
    }//GEN-LAST:event_LoginBtnActionPerformed
    private void userTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginBtn;
    private javax.swing.JComboBox cbx;
    private javax.swing.JLabel hiddenlbl1;
    private javax.swing.JLabel hiddenlbl2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel passtxt;
    private javax.swing.JPasswordField userPass;
    public static javax.swing.JTextField userText;
    private javax.swing.JLabel usernametxt;
    // End of variables declaration//GEN-END:variables
}
