
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pck;
import net.proteanit.sql.DbUtils;
import java.sql.*;
import javax.swing.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.Window;
import java.awt.image.BufferedImage;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author intel
 */
public class PickupdesignNewProduct extends javax.swing.JFrame {
    static Connection connection;
    static String url;
    static Statement st;
    static ResultSet rs;
    String dbtbl;
    static Statement st1;
    static ResultSet rs22;
    int count = 0;
    Connection Conn = null;
    ResultSet rs1 = null;
    ResultSet rs2 = null;
    ResultSet rs4 = null;
    PreparedStatement pst5 = null;
    PreparedStatement pst4 = null;
    PreparedStatement pst3 = null;
    PreparedStatement pst2 = null;
    PreparedStatement pst1 = null;
    PreparedStatement pst = null;
    private ImageIcon format = null;
    String id = "";
    
    public int search(String id, String name) throws SQLException, ClassNotFoundException{
        Class.forName("com.mysql.jdbc.Driver");
        url = "jdbc:mysql://localhost:3306/pos";
        connection = DriverManager.getConnection(url, "root", "");
        st = connection.createStatement();
        rs = st.executeQuery("Select * From admin Where adminID= '" + id + "'  " + "and fname = '" + name + "'");
        if (rs != null)
            return 1;
        else
            return 0;
    }
    
    public static class javaconnect{
        Connection Conn = null;
        
        public static Connection ConnecrDB(){
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection Conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pos","root","");
                return Conn;
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "error");
            }
            return null;
        }
    }
    
   
    /**
     * Creates new form CustomerAcc
     */
    public PickupdesignNewProduct(){
        initComponents();
        Conn = PickupdesignNewProduct.javaconnect.ConnecrDB();
        Update_table();
        //getId();
    }
    
    private static java.sql.Date getCurrentDate(){
        java.util.Date today = new java.util.Date();
        return new java.sql.Date(today.getTime());
    }
    
/*    private void getId(){
    String sum;
    try{
        String sql = "SELECT max(ProductID) FROM products";
        pst = Conn.prepareStatement(sql);       
        rs= pst.executeQuery();
        while(rs.next()){
            //rs.beforeFirst();
            sum = rs.getString("max(ProductID)");
            int identification = Integer.parseInt(sum)+1;
            productid.setText(Integer.toString(identification));
        }
    }
    catch (Exception e){
        int identification = Integer.parseInt(productid.getText())+1;
        productid.setText(Integer.toString(identification));
    }   
}*/
    
    public void getorders(){
        try{
            rs = pst.executeQuery();
            while(rs.next()){
                id = rs.getString("ProductID");
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void Update_table(){
        try{
            String sql = "select ProductID, ProductName, ProductPrice from products";
            pst = Conn.prepareStatement(sql);
            rs = pst.executeQuery();
            //tb.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch  (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        productname = new javax.swing.JTextField();
        description = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Quantity = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pickupDateChooser = new com.toedter.calendar.JDateChooser();
        unitCombo = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        category = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        userName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Add Product");
        jDesktopPane1.add(jLabel5);
        jLabel5.setBounds(40, 40, 220, 30);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel14.setText("Product Name:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(90, 60, 200, 23);

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel15.setText("Product Description:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(90, 90, 200, 23);

        jButton2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(330, 280, 170, 25);
        jPanel1.add(productname);
        productname.setBounds(310, 50, 230, 30);
        jPanel1.add(description);
        description.setBounds(310, 80, 230, 30);

        price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                priceKeyTyped(evt);
            }
        });
        jPanel1.add(price);
        price.setBounds(310, 110, 230, 30);

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel16.setText("Product Price:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(90, 120, 200, 23);

        Quantity.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Quantity.setText("Product Quantity:");
        jPanel1.add(Quantity);
        Quantity.setBounds(90, 150, 200, 23);

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel17.setText("Date:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(90, 240, 130, 23);

        pickupDateChooser.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(pickupDateChooser);
        pickupDateChooser.setBounds(310, 230, 230, 30);

        unitCombo.setBackground(new java.awt.Color(204, 255, 204));
        unitCombo.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        unitCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PCS", "Box", "Bundle" }));
        unitCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitComboActionPerformed(evt);
            }
        });
        jPanel1.add(unitCombo);
        unitCombo.setBounds(310, 203, 230, 30);

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel18.setText("Unit:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(90, 210, 37, 23);

        jButton3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(110, 280, 170, 25);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("Product Category");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 180, 210, 23);

        category.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                categoryKeyTyped(evt);
            }
        });
        jPanel1.add(category);
        category.setBounds(310, 170, 230, 30);

        quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quantityKeyTyped(evt);
            }
        });
        jPanel1.add(quantity);
        quantity.setBounds(310, 140, 230, 30);

        jDesktopPane1.add(jPanel1);
        jPanel1.setBounds(40, 110, 610, 370);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 550));

        userName.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameActionPerformed(evt);
            }
        });
        getContentPane().add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(684, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
      
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(productname.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Product Name Required!");
        else if(description.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Please add description");
        else if(price.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Please add price");            
        else if(quantity.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Please add Quantity");
        else if(category.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Please add Category");
        else if(pickupDateChooser.getDate().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter date");
        }
        else{
            try{
                url = "jdbc:mysql://localhost:3306/pos";
                connection = DriverManager.getConnection(url, "root", "");
                String sql = "INSERT INTO products (ProductID, ProductName, ProductDescription, ProductPrice, ProductQuantity, "
                        + "ProductCategory, ProductUnit, ProductDate) values(null,?,?,?,?,?,?,?)";
                pst = connection.prepareStatement(sql);
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
                String d = sdf.format(pickupDateChooser.getDate());
                int qty;
                
                double pricey = Double.parseDouble(price.getText());
                //st = Conn.prepareStatement(sql1);
                
//                pst.setString(1, productid.getText());
                pst.setString(1, productname.getText());
                pst.setString(2, description.getText());
                pst.setString(3, Double.toString(pricey));
                
                if(unitCombo.getSelectedItem().toString().equals("PCS")){
                    qty = Integer.parseInt(quantity.getText().trim());
                    pst.setString(4, Integer.toString(qty));
                }
                else if(unitCombo.getSelectedItem().toString().equals("Box")){
                    qty = Integer.parseInt(quantity.getText().trim())*50;
                    pst.setString(4, Integer.toString(qty));
                }
                else if(unitCombo.getSelectedItem().toString().equals("Bundle")){
                    qty = Integer.parseInt(quantity.getText().trim())*25;
                    pst.setString(4, Integer.toString(qty));
                }
                pst.setString(5, category.getText());
                pst.setString(6, unitCombo.getSelectedItem().toString());
                pst.setString(7, d);

                pst.execute();
                JOptionPane.showMessageDialog(null, "New product added");
 //               productid.setText(null);
                productname.setText(null);
                description.setText(null);
                price.setText(null);
                quantity.setText(null);
                category.setText(null); 
                this.dispose();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameActionPerformed

    private void unitComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitComboActionPerformed

    }//GEN-LAST:event_unitComboActionPerformed

    private void priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceKeyTyped
        char character = evt.getKeyChar();
        if (((character < '.') || (character > '9')) && (character != '\b')) {
                    evt.consume();
        }
    }//GEN-LAST:event_priceKeyTyped

    private void quantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityKeyTyped
        char character = evt.getKeyChar();
        if (((character < '0') || (character > '9'))&& (character != '\b')) {
                    evt.consume();
        }
    }//GEN-LAST:event_quantityKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void categoryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_categoryKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PickupdesignNewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PickupdesignNewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PickupdesignNewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PickupdesignNewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PickupdesignNewProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Quantity;
    private javax.swing.JTextField category;
    private javax.swing.JTextField description;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser pickupDateChooser;
    private javax.swing.JTextField price;
    private javax.swing.JTextField productname;
    private javax.swing.JTextField quantity;
    private javax.swing.JComboBox unitCombo;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
